OrderSystem/Controllers/LoginController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static DAL.Model.LoginModel;

namespace OrderSystem.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private LoginDao dao = new LoginDao();
        // GET: Login
        // 登入畫面
        public ActionResult Index()
        {

            
            ViewBag.ValidateCode = GetValidateCode();
            if (Session["Lang"] != null)
            {
                if (Session["Lang"].ToString().IndexOf("Chinese") >= 0)
                {
                    ViewBag.LangStr = "English";
                }
                else
                {
                    ViewBag.LangStr = "繁體中文";
                }
            }
            else
            {
                ViewBag.LangStr = "English";
                Session["Lang"] = "Chinese_Traditional";
            }
            return View();
        }

        /// <summary>
        /// 切換語言
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangeLang()
        {

            HttpCookie MyLang = new HttpCookie("MyLang");

            if (Session["Lang"].ToString().IndexOf("Chinese") >= 0)
            {
                MyLang.Value = "en-US";
                Response.Cookies.Add(MyLang);
                MyLang.Expires = DateTime.Now.AddDays(1);

                Session["Lang"] = "English";
            }
            else
            {
                MyLang.Value = null; //不指定語言預設為中文
                Response.Cookies.Add(MyLang);
                MyLang.Expires = DateTime.Now.AddDays(1);

                Session["Lang"] = "Chinese_Traditional";
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// 登入
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public UserInfo Login(string USER_ID, string USER_PWD)
        {
            return dao.Login(USER_ID, USER_PWD);
        }

        /// <summary>
        /// 取得驗證碼
        /// </summary>
        /// <returns></returns>
        public string GetValidateCode()
        {
            int iFirst = 0;
            string ResultStr = String.Empty;
            int[] rtArray = new Int32[4];

            Random ro = new Random(4 * unchecked((int)DateTime.Now.Ticks));
            iFirst = ro.Next(49, 90);
            rtArray[0] = iFirst;

            for (int i = 1; i < 4; i++)
            {
                Random ri = new Random(i * iFirst * unchecked((int)DateTime.Now.Ticks));
                rtArray[i] = ri.Next(49, 90);
                if (rtArray[i] == 4)
                {
                    rtArray[i] = 8;
                }
                iFirst = rtArray[i];
            }

            for (int i = 0; i < 4; i++)
            {
                if (rtArray[i] > 57 && rtArray[i] < 65)
                {
                    rtArray[i] += 7;
                }
                ResultStr += ((char)rtArray[i]).ToString();
            }
            Session["ValidateCode"] = ResultStr;
            return ResultStr;
        }

        /// <summary>
        /// 登出
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            Session.Clear();

            return RedirectToAction("Index");
        }
    }
}

OrderSystem/Views/Shared/FrameLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FrameLayout</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue")
</head>
<body>
    <div> 
        @RenderBody()
    </div>
    
</body>
</html>

OrderSystem/Views/Shared/_Layout.cshtml
@using Common.Util;


<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FSE 雲端物流系統</title>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue")
    @Styles.Render("~/Content/css")

</head>
<body>
    @RenderBody()
    <div id="app" class="h-100">
        <el-container>
            <el-header height="">
                <h1 class="title">
                    雲端物流系統
                </h1>
                <div class="info_wrap">
                    <div class="info_item">
                        <img src="~/Content/images/icon_avatar_defualt_user.svg" />
                        <span>@SessionUtil.Current.UserName</span>
                    </div>
                    <div class="info_item">
                        <button type="button" class="btn_logout" onclick="location.href='@Url.Action("Logout","Login")'">LOGOUT</button>
                    </div>
                </div>
            </el-header>
            <el-container>
                <el-aside>
                    @{Html.RenderAction("Menu", "Home"); }
                </el-aside>
                <el-main>
                    <el-tabs id="tab" v-model="editableTabsValue" type="card" closable @@edit="handleTabsEdit">
                        <el-tab-pane :key="item.name"
                                     v-for="(item, index) in editableTabs"
                                     :label="item.title"
                                     :name="item.name">
                            <div class="container-tab" v-html="item.content"></div>
                        </el-tab-pane>
                    </el-tabs>
                </el-main>
            </el-container>
        </el-container>
    </div>
    <script>
        $(function () {
            var vm = new Vue({
                el: '#app',
                data: {
                    editableTabsValue: '0',
                    editableTabs: [],
                    tabIndex: 0
                },
                methods: {
                    handleTabsEdit(targetName, action) {
                        if (action === 'add') {

                        }
                        if (action === 'remove') {
                            let tabs = this.editableTabs;
                            let activeName = this.editableTabsValue;
                            if (activeName === targetName) {
                                tabs.forEach((tab, index) => {
                                    if (tab.name === targetName) {
                                        let nextTab = tabs[index + 1] || tabs[index - 1];
                                        if (nextTab) {
                                            activeName = nextTab.name;
                                        }
                                    }
                                });
                            }

                            this.editableTabsValue = activeName;
                            this.editableTabs = tabs.filter(tab => tab.name !== targetName);
                        }
                    },
                    handleOpen(key, keyPath) {
                        console.log(key, keyPath);
                    },
                    handleClose(key, keyPath) {
                        console.log(key, keyPath);
                    },
                    handleSelect(key, keyPath) {
                        var addr = key.split('|')[0];
                        var title = key.split('|')[1];
                        var isExist = false
                        vm.editableTabs.forEach(
                            element => {
                                if (element.title == title) {
                                    isExist = true;
                                }
                            }
                        );
                        if (!isExist) {
                            vm.editableTabs.push({
                                title: title,
                                name: title,
                                content: "<iframe class='responsive-iframe' src='" + addr + "' ></iframe>"
                            });
                            //"<iframe class='responsive-iframe' name='mainframe' id='mainframe' src='" + addr + "' width='100%' marginwidth='0' marginheight='0' scrolling='Yes' frameborder='0' onload='Javascript:SetCwinHeight()'></iframe>"
                        }
                        vm.editableTabsValue = title;
                    }
                }
            });
        });

        function SetCwinHeight() {
            var iframeid = document.getElementById("mainframe"); //iframe id  
            if (document.getElementById) {
                if (iframeid && !window.opera) {
                    if (iframeid.contentDocument && iframeid.contentDocument.body.offsetHeight) {
                        iframeid.height = iframeid.contentDocument.body.offsetHeight;
                    } else if (iframeid.Document && iframeid.Document.body.scrollHeight) {
                        iframeid.height = iframeid.Document.body.scrollHeight;
                    }
                }
            }
        }
    </script>
</body>
</html>